### PR TITLE
Debt Score Sparklines

### LINKED ISSUE #7: Cache the debt score of every project for every day and can show a line graph of each project's debt over time

### PR DESCRIPTION
**Pull request by heggern**
Added package `davaxi/sparkline` to be able to draw the graph directly from the blade file, without a bunch of npm packages.

Caching the Dept Score for an hour, same as `App\Projects`

Closes #7

### CODE REVIEW

**Comment by mattstauffer** [comment]
@heggern Thanks so much!  Would you mind throwing a few screenshots in here? It'll help me when it comes time to review it. Thanks!

**Comment by heggern** [comment]
@mattstauffer Sure thing!
ozzie-sparklines

**Comment by mattstauffer** [comment]
Sorry for the delay. Great work @heggern!!

**Comment by heggern** [comment]
Thanks. Happy to be able to contribute.

**Pull request merged**
