### PR TITLE
Laravel 10.x Shift

### PR DESCRIPTION
**Pull request by driftingly**
This pull request includes the changes for upgrading to Laravel 10.x. Feel free to commit any additional changes to the `shift-91983` branch.

**Before merging**, you need to:

- Checkout the `shift-91983` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by driftingly** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/tighten/ozzie/pull/208/commits/4b5565e88c9d061f4b513c3330a4df56dedb5779?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert 4b5565e8` and make the [config file changes](https://github.com/laravel-shift/laravel-9.x/pull/4/commits/5401110f1f41793ecdce268495768abfa4a53dfe) manually.

**Comment by driftingly** [comment]
:information_source: Shift [updated your dependencies](https://github.com/tighten/ozzie/pull/208/commits/19e247ca12dd071baee1c89bbd285e9b5fd2dd7c?w=1) for Laravel 10. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 10. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [graham-campbell/github](https://packagist.org/packages/graham-campbell/github)
- [ ] [laravel/ui](https://packagist.org/packages/laravel/ui)

**Comment by driftingly** [comment]
:warning: Laravel 10 has added a return type of `array` to the Event `broadcastOn` and Notification `via` methods. However, you may still return a single channel from these methods.

Shift added the `array` return type to these methods in the following classes. You should review them to ensure you are returning an `array`, or remove the return type.

- [ ] app/Notifications/SendOzzieStats.php

**Comment by driftingly** [comment]
:information_source: Laravel 10 added PHP type hints to all user-land code included in a new Laravel application. In an effort to modernize your code, Shift [added type hints](https://github.com/tighten/ozzie/pull/208/commits/5e5f431dfbe86bd31e64c490b6902fd3127e1265?w=1) to any method which is used by Laravel.

**Comment by driftingly** [comment]
:information_source: Now with type hints in your code, defining types within PHP DocBlocks is redundant. Laravel has removed all of the `@param` and `@return` tags from its DocBlocks where types are defined with PHP. Similarly, Shift [removed these tags](https://github.com/tighten/ozzie/pull/208/commits/9355a458b509fe8e1bcacb91320276c0c8e3fb1b?w=1) from any DocBlock where the code now has _equivalent_ type hints.

**Comment by driftingly** [comment]
:information_source: Shift understands developers have different preferences when it comes to type hints. All of Shift's automation is done in nice, atomic commits. This makes it easier to undo any of the changes Shift makes.

If you wish to undo the changes relating to type hints, you may run:

- `git revert 9355a45` to revert the DocBlock changes.
- `git revert aadadff` to revert the type hints added from DocBlocks.
- `git revert 5e5f431` to revert the type hints added for Laravel 10.

**Comment by driftingly** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6.2. Shift detected references to Symfony classes within your application. You should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.2.md) for any additional changes.

**Comment by driftingly** [comment]
:warning: Laravel 10 requires Composer 2.2 or higher. You should verify the Composer version in your environments by running `composer --version` to ensure it meets this new requirement. If necessary, run `composer self-update` to update Composer.

**Comment by driftingly** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Review by jakebathman — APPROVED** [review]

**Pull request merged**
